name: ChatOps
on: issue_comment # this is used for PRs https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review

env:
  MAGIC_COMMENT: "/wandb" # this is a parameter you can change

jobs:
  see-comment:
    # this filters for only comments made on a pull request and if the magic comment is detected
    if: (github.event.issue.pull_request != null)
    runs-on: ubuntu-latest
    steps:
    - name: see payload # this step is for debugging purposes only, so you can see the payload. 
      run: echo "PAYLOAD:\n${PAYLOAD}\n"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}
    - name: filter for magic comment
      id: filter
      if: contains(github.event.comment.body, env.MAGIC_COMMENT)
      run: echo "magic comment detected"
    - name: Parse value from the magic command
      if: steps.filter.outcome == 'success'
      id: get-magic-value
      shell: python
      run: |
        import re, os
        match = re.search('${{env.MAGIC_COMMENT}}[\s+](\S+)', "${{ github.event.comment.body }}")
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
          if match:
            print(f'VAL_FOUND=true', file=fh)
            print(f'MAGIC_VAL={match.group(1)}', file=fh)
          else:
            print(f'VAL_FOUND=false', file=fh)
    - name: print value of magic command
      if:  steps.get-magic-value.outcome == 'success' && steps.get-magic-value.outputs.VAL_FOUND == 'true'
      run: echo "the value is ${{ steps.get-magic-value.outputs.MAGIC_VAL }}"
