name: ChatOps
on: issue_comment # this is used for PRs https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review

jobs:
  see-comment:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ github.event.comment.body }}"
    - name: see payload
      run: |
        echo "PAYLOAD:\n${PAYLOAD}\n"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}
    - name: another key body
      if: github.event.issue.pull_request
      run: echo "does this run"
